package cli

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

// runCompletion emits a static shell completion script for amq-squad.
// Supported shells: bash, zsh, fish. The script goes to stdout only;
// usage/help/errors stay on stderr to match the rest of the CLI.
func runCompletion(args []string) error {
	fs := flag.NewFlagSet("completion", flag.ContinueOnError)
	fs.Usage = func() {
		fmt.Fprint(os.Stderr, `amq-squad completion - emit a shell completion script

Usage:
  amq-squad completion bash
  amq-squad completion zsh
  amq-squad completion fish

Pipe the output into the appropriate location for your shell, e.g.:
  amq-squad completion bash > /etc/bash_completion.d/amq-squad
  amq-squad completion zsh  > "${fpath[1]}/_amq-squad"
  amq-squad completion fish > ~/.config/fish/completions/amq-squad.fish

Examples:
  amq-squad completion bash
  amq-squad completion zsh > "${fpath[1]}/_amq-squad" && compinit
`)
	}
	if err := parseFlags(fs, args); err != nil {
		return err
	}
	if fs.NArg() == 0 {
		return usageErrorf("completion requires a shell: bash, zsh, or fish")
	}
	if fs.NArg() > 1 {
		return usageErrorf("completion takes exactly one shell argument; got %d", fs.NArg())
	}
	switch fs.Arg(0) {
	case "bash":
		fmt.Print(bashCompletionScript)
	case "zsh":
		fmt.Print(zshCompletionScript)
	case "fish":
		fmt.Print(fishCompletionScript)
	default:
		return usageErrorf("unsupported shell %q: use bash, zsh, or fish", fs.Arg(0))
	}
	return nil
}

// completionTopCommands lists the top-level public verbs included in the
// generated completion scripts. Kept in sync with cli.go dispatch by the
// completion tests, which assert representative entries appear in each
// shell's output.
var completionTopCommands = []string{
	"team",
	"up",
	"stop",
	"down",
	"status",
	"console",
	"noc",
	"history",
	"resume",
	"fork",
	"rm",
	"archive",
	"agent",
	"completion",
	"doctor",
	"version",
	"help",
}

// completionAgentSubcommands lists the `amq-squad agent` subcommands.
var completionAgentSubcommands = []string{
	"up",
	"resume",
}

// completionTeamSubcommands lists the `amq-squad team` subcommands.
var completionTeamSubcommands = []string{
	"init",
	"resume",
	"rules",
	"sync",
	"profiles",
}

// completionTeamRulesSubcommands lists `amq-squad team rules` subcommands.
var completionTeamRulesSubcommands = []string{
	"init",
}

// completionCommonFlags lists every flag registered by the current stdlib
// CLI surfaces. The list is exhaustive on purpose: shell completion
// shouldn't omit a flag just because it only appears on one command. Drift
// guard: `TestCompletionFlagsCoverDispatcher` walks the source tree and
// fails if a `flag.NewFlagSet` declares a flag missing here.
var completionCommonFlags = []string{
	// Root flags (also offered as first-word completions when the user
	// starts typing `-...` before picking a subcommand).
	"--help",
	"-h",
	"--version",
	"-v",
	"--quiet",
	"--verbose",
	"--color",
	"-y",
	// Subcommand flags, sorted alphabetically.
	"--all",
	"--allow-outside",
	"--apply",
	"--as",
	"--at-risk-wait",
	"--binary",
	"--claude-args",
	"--codex-args",
	"--conversation",
	"--conversation-id",
	"--cwd",
	"--depth",
	"--dry-run",
	"--exec",
	"--force",
	"--force-duplicate",
	"--fresh",
	"--from",
	"--handle",
	"--hide-stale",
	"--json",
	"--launcher",
	"--launcher-args",
	"--layout",
	"--me",
	"--model",
	"--no-attach",
	"--no-bootstrap",
	"--no-default-args",
	"--once",
	"--personas",
	"--profile",
	"--project",
	"--refresh",
	"--reset",
	"--restore-existing",
	"--review-age",
	"--role",
	"--roles",
	"--root",
	"--seed-from",
	"--session",
	"--stagger",
	"--stale-after",
	"--target",
	"--team-home",
	"--team-profile",
	"--team-workstream",
	"--terminal",
	"--terminal-session",
	"--tree",
	"--trust",
	"--yes",
}

var (
	bashCompletionScript = buildBashCompletionScript()
	zshCompletionScript  = buildZshCompletionScript()
	fishCompletionScript = buildFishCompletionScript()
)

func buildBashCompletionScript() string {
	var b strings.Builder
	b.WriteString("# amq-squad bash completion\n")
	b.WriteString("# Generated by `amq-squad completion bash`. Source this file or place it\n")
	b.WriteString("# under /etc/bash_completion.d/.\n\n")
	b.WriteString("_amq_squad_complete() {\n")
	b.WriteString("    local cur prev words cword\n")
	b.WriteString("    if declare -F _get_comp_words_by_ref >/dev/null; then\n")
	b.WriteString("        _get_comp_words_by_ref -n =: cur prev words cword\n")
	b.WriteString("    else\n")
	b.WriteString("        cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	b.WriteString("        prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	b.WriteString("        words=(\"${COMP_WORDS[@]}\")\n")
	b.WriteString("        cword=$COMP_CWORD\n")
	b.WriteString("    fi\n\n")
	b.WriteString("    local top_commands=\"")
	b.WriteString(strings.Join(completionTopCommands, " "))
	b.WriteString("\"\n")
	b.WriteString("    local team_subcommands=\"")
	b.WriteString(strings.Join(completionTeamSubcommands, " "))
	b.WriteString("\"\n")
	b.WriteString("    local common_flags=\"")
	b.WriteString(strings.Join(completionCommonFlags, " "))
	b.WriteString("\"\n\n")
	b.WriteString("    if [ \"$cword\" -eq 1 ]; then\n")
	b.WriteString("        if [[ \"$cur\" == -* ]]; then\n")
	b.WriteString("            COMPREPLY=( $(compgen -W \"$common_flags\" -- \"$cur\") )\n")
	b.WriteString("        else\n")
	b.WriteString("            COMPREPLY=( $(compgen -W \"$top_commands\" -- \"$cur\") )\n")
	b.WriteString("        fi\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n\n")
	b.WriteString("    if [ \"${words[1]}\" = \"team\" ] && [ \"$cword\" -eq 2 ]; then\n")
	b.WriteString("        COMPREPLY=( $(compgen -W \"$team_subcommands\" -- \"$cur\") )\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n\n")
	b.WriteString("    if [ \"${words[1]}\" = \"team\" ] && [ \"${words[2]}\" = \"rules\" ] && [ \"$cword\" -eq 3 ]; then\n")
	b.WriteString("        COMPREPLY=( $(compgen -W \"")
	b.WriteString(strings.Join(completionTeamRulesSubcommands, " "))
	b.WriteString("\" -- \"$cur\") )\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n\n")
	b.WriteString("    if [ \"${words[1]}\" = \"agent\" ] && [ \"$cword\" -eq 2 ]; then\n")
	b.WriteString("        COMPREPLY=( $(compgen -W \"")
	b.WriteString(strings.Join(completionAgentSubcommands, " "))
	b.WriteString("\" -- \"$cur\") )\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n\n")
	b.WriteString("    if [[ \"$cur\" == -* ]]; then\n")
	b.WriteString("        COMPREPLY=( $(compgen -W \"$common_flags\" -- \"$cur\") )\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n")
	b.WriteString("}\n\n")
	b.WriteString("complete -F _amq_squad_complete amq-squad\n")
	return b.String()
}

func buildZshCompletionScript() string {
	var b strings.Builder
	b.WriteString("#compdef amq-squad\n")
	b.WriteString("# amq-squad zsh completion\n")
	b.WriteString("# Generated by `amq-squad completion zsh`. Place under a directory in\n")
	b.WriteString("# your $fpath, e.g. \"${fpath[1]}/_amq-squad\", then `compinit`.\n\n")
	b.WriteString("_amq_squad() {\n")
	b.WriteString("    local -a top_commands team_subcommands common_flags\n")
	b.WriteString("    top_commands=(")
	for i, c := range completionTopCommands {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(zshQuote(c))
	}
	b.WriteString(")\n")
	b.WriteString("    team_subcommands=(")
	for i, c := range completionTeamSubcommands {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(zshQuote(c))
	}
	b.WriteString(")\n")
	b.WriteString("    common_flags=(")
	for i, f := range completionCommonFlags {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(zshQuote(f))
	}
	b.WriteString(")\n\n")
	b.WriteString("    if (( CURRENT == 2 )); then\n")
	b.WriteString("        if [[ \"${words[CURRENT]}\" == -* ]]; then\n")
	b.WriteString("            compadd -- \"${common_flags[@]}\"\n")
	b.WriteString("        else\n")
	b.WriteString("            compadd -- \"${top_commands[@]}\"\n")
	b.WriteString("        fi\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n\n")
	b.WriteString("    if [[ \"${words[2]}\" == \"team\" && CURRENT -eq 3 ]]; then\n")
	b.WriteString("        compadd -- \"${team_subcommands[@]}\"\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n\n")
	b.WriteString("    if [[ \"${words[2]}\" == \"team\" && \"${words[3]}\" == \"rules\" && CURRENT -eq 4 ]]; then\n")
	b.WriteString("        compadd -- ")
	for i, s := range completionTeamRulesSubcommands {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(zshQuote(s))
	}
	b.WriteString("\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n\n")
	b.WriteString("    if [[ \"${words[2]}\" == \"agent\" && CURRENT -eq 3 ]]; then\n")
	b.WriteString("        compadd -- ")
	for i, s := range completionAgentSubcommands {
		if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(zshQuote(s))
	}
	b.WriteString("\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n\n")
	b.WriteString("    if [[ \"${words[CURRENT]}\" == -* ]]; then\n")
	b.WriteString("        compadd -- \"${common_flags[@]}\"\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n")
	b.WriteString("}\n\n")
	b.WriteString("compdef _amq_squad amq-squad\n")
	return b.String()
}

func buildFishCompletionScript() string {
	var b strings.Builder
	b.WriteString("# amq-squad fish completion\n")
	b.WriteString("# Generated by `amq-squad completion fish`. Place under\n")
	b.WriteString("# ~/.config/fish/completions/amq-squad.fish.\n\n")
	b.WriteString("function __amq_squad_no_subcommand\n")
	b.WriteString("    set -l tokens (commandline -opc)\n")
	b.WriteString("    if test (count $tokens) -le 1\n")
	b.WriteString("        return 0\n")
	b.WriteString("    end\n")
	b.WriteString("    return 1\n")
	b.WriteString("end\n\n")
	for _, c := range completionTopCommands {
		fmt.Fprintf(&b, "complete -c amq-squad -n __amq_squad_no_subcommand -a %s\n", fishQuote(c))
	}
	b.WriteString("\n")
	for _, sub := range completionTeamSubcommands {
		fmt.Fprintf(&b, "complete -c amq-squad -n \"__fish_seen_subcommand_from team\" -a %s\n", fishQuote(sub))
	}
	b.WriteString("\n")
	for _, sub := range completionTeamRulesSubcommands {
		fmt.Fprintf(&b, "complete -c amq-squad -n \"__fish_seen_subcommand_from rules\" -a %s\n", fishQuote(sub))
	}
	b.WriteString("\n")
	for _, sub := range completionAgentSubcommands {
		fmt.Fprintf(&b, "complete -c amq-squad -n \"__fish_seen_subcommand_from agent\" -a %s\n", fishQuote(sub))
	}
	b.WriteString("\n")
	for _, f := range completionCommonFlags {
		switch {
		case strings.HasPrefix(f, "--"):
			fmt.Fprintf(&b, "complete -c amq-squad -l %s\n", fishQuote(strings.TrimPrefix(f, "--")))
		case strings.HasPrefix(f, "-") && len(f) == 2:
			fmt.Fprintf(&b, "complete -c amq-squad -s %s\n", fishQuote(strings.TrimPrefix(f, "-")))
		}
	}
	return b.String()
}

// zshQuote wraps a value in single quotes for the zsh completion script.
// The inputs are static command/flag names and contain no characters that
// need escaping beyond surrounding the value in quotes.
func zshQuote(s string) string {
	return "'" + s + "'"
}

// fishQuote single-quotes a value for fish.
func fishQuote(s string) string {
	return "'" + s + "'"
}
